server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root123
  redis:
    database: 0
#    sentinel:
#      master: mymaster
#      nodes:
#        - "127.0.0.1:26379"
#        - "127.0.0.1:26380"
#        - "127.0.0.1:26381"
#      checkSentinelsList: false
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  redisson:
    config: |
      sentinelServersConfig:
        sentinelAddresses:
          - "redis://127.0.0.1:26379"
          - "redis://127.0.0.1:26380"
          - "redis://127.0.0.1:26381"
        masterName: "mymaster"
        checkSentinelsList: false
        database: 0
        connectTimeout: 10000
        timeout: 3000
        retryAttempts: 3
        retryInterval: 1500
        failedSlaveReconnectionInterval: 3000
        failedSlaveCheckInterval: 30000
        masterConnectionMinimumIdleSize: 1
        masterConnectionPoolSize: 10
        slaveConnectionMinimumIdleSize: 1
        slaveConnectionPoolSize: 10
        idleConnectionTimeout: 10000
        pingConnectionInterval: 30000
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    listener:
      simple:
        prefetch: 10 # 每个消费者最多同时处理10条消息
        acknowledge-mode: manual # 开启手动确认
        publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
        publisher-returns: true # 开启publisher return机制
  elasticsearch:
    uris: http://127.0.0.1:9200
    username: elastic
    password: changeme
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
hm:
  jwt:
      #    # 设置jwt签名加密时使用的秘钥
      #    admin-secret-key: itcast
      #    # 设置jwt过期时间
      #    admin-ttl: 7200000
      #    # 设置前端传递过来的令牌名称
      #    admin-token-name: token
    user-secret-key: ThisIsA32BytesLongSecretKeyForHS256
    user-ttl: 7200000
    user-token-name: authorization
  rate-limiter:
    order-processing: 100
canal:
    server: 127.0.0.1:11111
    destination: example
    batch-size: 1000
    timeout: 1
    unit: seconds
    username: canal
    password: canal
    filter: ".*\\..*"