---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zz.
--- DateTime: 2025/9/28 15:44
---
---参数列表
---1. 优惠券id
local voucherId = ARGV[1]
---2. 用户id
local userId = ARGV[2]
---3. 库存id
local stockKey = 'seckill:stock:' .. voucherId
---4. 订单id
local orderId = 'seckill:order:' .. voucherId

---业务
---1.从redis查询库存
local stock = redis.call('get', stockKey)
---2. 判断库存是否充足
if(not stock or tonumber(stock) <= 0) then
  return 1
end
---3. 如果充足，减库存
---3.1 查看用户是否购买过
---3.2 如果购买过，返回失败
if(redis.call('sismember', orderId, userId) == 1) then
  return 2
end
---3.3 如果未购买过，减库存，下单，返回成功
redis.call('decr', stockKey)
redis.call('sadd', orderId, userId)
return 0