---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zz.
--- DateTime: 2025/9/25 23:03
--- 解锁脚本
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0
